#!/bin/sh -e

export DESTDIR="$1"

meson \
    --prefix=/usr \
    --buildtype=release \
    -Dx11=disabled \
    -Dglx=disabled \
    -Dtls=disabled \
    build

ninja -C build
ninja -C build install
