#!/bin/sh -e

export DESTDIR="$1"

patch -p0 < pointer.patch
patch -p0 < hardcode.patch

meson \
    --prefix=/usr \
    -Dbuildtype=release \
    -Db_lto=true \
    build

ninja -C build

ninja -C build install
